# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://katzgov.github.io'
baseurl: '/katzgov-web'
title: 'Katz Government Affairs'
description: 'Katz Government Affairs, LLC'
permalink: pretty
logo: "/katz_government_affairs_llc_logo.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Our Team
  url: /team/
- title: Our Clients
  url: /clients/
- title: Contact
  url: /contact/
- title: The KGA Bulletin
  url: /blog/

# Footer nav
navigation_footer:
- title: LinkedIn
  url: "https://www.linkedin.com/company/katz-government-affairs-llc"
- title: Back to top
  url: "#top"

# Footer contact info
footer_text: |
  Katz Government Affairs, LLC<br>
  154 West State Street, Trenton, NJ 08608<br>
  Phone: (609) 392-7070

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "KGA Milestones"
    feature_text: |
      ## The KGA Bulletin
    feature_image: "/statehouse-506x495.jpg"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
